// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://miybwidaqwwhqvnotqkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1peWJ3aWRhcXd3aHF2bm90cWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNDI5MjAsImV4cCI6MjA1MTYxODkyMH0.i32NBTLbTo8tktNcB159PV-bylZzs121qIPN-4R5ZQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);